#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : connman
Version  : 1.38
Release  : 33
URL      : https://www.kernel.org/pub/linux/network/connman/connman-1.38.tar.xz
Source0  : https://www.kernel.org/pub/linux/network/connman/connman-1.38.tar.xz
Summary  : Connection Manager
Group    : Development/Tools
License  : GPL-2.0
Requires: connman-bin = %{version}-%{release}
Requires: connman-config = %{version}-%{release}
Requires: connman-data = %{version}-%{release}
Requires: connman-lib = %{version}-%{release}
Requires: connman-license = %{version}-%{release}
Requires: connman-man = %{version}-%{release}
Requires: connman-services = %{version}-%{release}
Requires: linux-firmware-wifi
BuildRequires : linux-firmware-wifi
BuildRequires : ncurses-dev
BuildRequires : openconnect-dev
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(libnftnl)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(xtables)
BuildRequires : readline-dev
BuildRequires : wpa_supplicant

%description
Connection Manager
******************
Functionality and features
==========================

%package bin
Summary: bin components for the connman package.
Group: Binaries
Requires: connman-data = %{version}-%{release}
Requires: connman-config = %{version}-%{release}
Requires: connman-license = %{version}-%{release}
Requires: connman-services = %{version}-%{release}

%description bin
bin components for the connman package.


%package config
Summary: config components for the connman package.
Group: Default

%description config
config components for the connman package.


%package data
Summary: data components for the connman package.
Group: Data

%description data
data components for the connman package.


%package dev
Summary: dev components for the connman package.
Group: Development
Requires: connman-lib = %{version}-%{release}
Requires: connman-bin = %{version}-%{release}
Requires: connman-data = %{version}-%{release}
Provides: connman-devel = %{version}-%{release}
Requires: connman = %{version}-%{release}

%description dev
dev components for the connman package.


%package lib
Summary: lib components for the connman package.
Group: Libraries
Requires: connman-data = %{version}-%{release}
Requires: connman-license = %{version}-%{release}

%description lib
lib components for the connman package.


%package license
Summary: license components for the connman package.
Group: Default

%description license
license components for the connman package.


%package man
Summary: man components for the connman package.
Group: Default

%description man
man components for the connman package.


%package services
Summary: services components for the connman package.
Group: Systemd services

%description services
services components for the connman package.


%prep
%setup -q -n connman-1.38
cd %{_builddir}/connman-1.38

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585253581
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1585253581
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/connman
cp %{_builddir}/connman-1.38/COPYING %{buildroot}/usr/share/package-licenses/connman/a7a897a4bde987e597c04f16a9c28f6d3f57916d
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/connman-vpnd
/usr/bin/connmanctl
/usr/bin/connmand
/usr/bin/connmand-wait-online

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/connman_resolvconf.conf

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/net.connman.vpn.service
/usr/share/dbus-1/system.d/connman-vpn-dbus.conf
/usr/share/dbus-1/system.d/connman.conf

%files dev
%defattr(-,root,root,-)
/usr/include/connman/acd.h
/usr/include/connman/agent.h
/usr/include/connman/device.h
/usr/include/connman/inet.h
/usr/include/connman/inotify.h
/usr/include/connman/ipaddress.h
/usr/include/connman/ipconfig.h
/usr/include/connman/log.h
/usr/include/connman/machine.h
/usr/include/connman/network.h
/usr/include/connman/notifier.h
/usr/include/connman/peer.h
/usr/include/connman/plugin.h
/usr/include/connman/provision.h
/usr/include/connman/resolver.h
/usr/include/connman/service.h
/usr/include/connman/session.h
/usr/include/connman/storage.h
/usr/include/connman/tethering.h
/usr/include/connman/version.h
/usr/lib64/pkgconfig/connman.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/connman/plugins-vpn/wireguard.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/connman/a7a897a4bde987e597c04f16a9c28f6d3f57916d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/connmanctl.1
/usr/share/man/man5/connman-service.config.5
/usr/share/man/man5/connman-vpn-provider.config.5
/usr/share/man/man5/connman-vpn.conf.5
/usr/share/man/man5/connman.conf.5
/usr/share/man/man8/connman-vpn.8
/usr/share/man/man8/connman.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/connman-vpn.service
/usr/lib/systemd/system/connman-wait-online.service
/usr/lib/systemd/system/connman.service
